module.exports = {
	length: a => a.length,
	indexOf: ([a, e]) => a.indexOf(e),
	slice: ([a, [i, j]]) => a.slice(i, j),
	push: ([a, e]) => a.push(...e),
	pop: a => a.pop(),
	unshift: ([a, e]) => a.unshift(...e),
	shift: a => a.shift(),
	splice: ([a, [i, l, b]]) => a.splice(i, l, ...b),
	concat: ([a, b]) => a.concat(...b),
	forEach: ([a, f]) => a.forEach((e, i, a) => f([e, i, a])),
	map: ([a, f]) => a.map((e, i, a) => f([e, i, a])),
	find: ([a, f]) => a.find((e, i, a) => f([e, i, a])),
	findIndex: ([a, f]) => a.findIndex((e, i, a) => f([e, i, a])),
	filter: ([a, f]) => a.filter((e, i, a) => f([e, i, a])),
	reduce: ([a, [f, v0]]) => a.reduce((v, e, i, a) => f([v, e, i, a]), v0),
	reduceRight: ([a, [f, v0]]) => a.reduceRight((v, e, i, a) => f([v, e, i, a]), v0),
	every: ([a, f]) => a.every((e, i, a) => f([e, i, a])),
	some: ([a, f]) => a.some((e, i, a) => f([e, i, a])),
	sort: ([a, f]) => a.sort((a, b) => f([a, b]))
};
